[project]
name = "voice-controlled-drone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "scipy>=1.16.2",
    "sounddevice>=0.5.2",
    "whisper>=1.1.10",
]
